# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-17 05:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projectmanagement', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('budgetmanagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tranche',
            name='recommended_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projectmanagement.UserProfile'),
        ),
        migrations.AddField(
            model_name='supercategory',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projectmanagement.Project'),
        ),
        migrations.AddField(
            model_name='projectbudgetperiodconf',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectmanagement.Project'),
        ),
        migrations.AddField(
            model_name='historicaltranche',
            name='budget_period',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='budgetmanagement.ProjectBudgetPeriodConf'),
        ),
        migrations.AddField(
            model_name='historicaltranche',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaltranche',
            name='recommended_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='projectmanagement.UserProfile'),
        ),
        migrations.AddField(
            model_name='historicalsupercategory',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalsupercategory',
            name='project',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='projectmanagement.Project'),
        ),
        migrations.AddField(
            model_name='historicalbudgetperiodunit',
            name='budget_heading',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='budgetmanagement.BudgetCategory'),
        ),
        migrations.AddField(
            model_name='historicalbudgetperiodunit',
            name='budget_period',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='budgetmanagement.ProjectBudgetPeriodConf'),
        ),
        migrations.AddField(
            model_name='historicalbudgetperiodunit',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='projectmanagement.UserProfile'),
        ),
        migrations.AddField(
            model_name='historicalbudgetperiodunit',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='budgetperiodunit',
            name='budget_heading',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='budgetmanagement.BudgetCategory'),
        ),
        migrations.AddField(
            model_name='budgetperiodunit',
            name='budget_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='budgetmanagement.ProjectBudgetPeriodConf'),
        ),
        migrations.AddField(
            model_name='budgetperiodunit',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projectmanagement.UserProfile'),
        ),
        migrations.AddField(
            model_name='budgetcategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='budgetmanagement.BudgetCategory'),
        ),
        migrations.AddField(
            model_name='budgetcategory',
            name='super_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budgetmanagement.SuperCategory'),
        ),
    ]
