# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-19 10:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projectmanagement', '0002_auto_20170817_0716'),
        ('budgetmanagement', '0002_auto_20170817_0532'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.PositiveIntegerField(choices=[(0, b'Inactive'), (2, b'Active')], default=2)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(0, b''), (1, b'Requested'), (2, b'Request more information'), (3, b'Reject'), (4, b'Approved')], default=0)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('actual_start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('financial_type', models.IntegerField(choices=[(1, b'Yearly'), (2, b'Quarterly'), (3, b'Half Yearly')], default=2)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectmanagement.Project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricalBudget',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('active', models.PositiveIntegerField(choices=[(0, b'Inactive'), (2, b'Active')], default=2)),
                ('created', models.DateTimeField(blank=True, editable=False)),
                ('modified', models.DateTimeField(blank=True, editable=False)),
                ('status', models.IntegerField(choices=[(0, b''), (1, b'Requested'), (2, b'Request more information'), (3, b'Reject'), (4, b'Approved')], default=0)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('actual_start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('financial_type', models.IntegerField(choices=[(1, b'Yearly'), (2, b'Quarterly'), (3, b'Half Yearly')], default=2)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='projectmanagement.Project')),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
                'verbose_name': 'historical budget',
            },
        ),
        migrations.CreateModel(
            name='HistoricalProjectBudgetPeriodConf',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('active', models.PositiveIntegerField(choices=[(0, b'Inactive'), (2, b'Active')], default=2)),
                ('created', models.DateTimeField(blank=True, editable=False)),
                ('modified', models.DateTimeField(blank=True, editable=False)),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('budget', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='budgetmanagement.Budget')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='projectmanagement.Project')),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
                'verbose_name': 'historical project budget period conf',
            },
        ),
        migrations.RemoveField(
            model_name='budgetcategory',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='budgetcategory',
            name='super_category',
        ),
        migrations.RemoveField(
            model_name='budgetperiodunit',
            name='budget_heading',
        ),
        migrations.RemoveField(
            model_name='historicalbudgetperiodunit',
            name='budget_heading',
        ),
        migrations.AddField(
            model_name='budgetperiodunit',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='budgetmanagement.SuperCategory'),
        ),
        migrations.AddField(
            model_name='budgetperiodunit',
            name='expenses_type',
            field=models.IntegerField(blank=True, choices=[(1, b'Programmatic'), (2, b'Non-programmatic')], null=True),
        ),
        migrations.AddField(
            model_name='budgetperiodunit',
            name='heading',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projectmanagement.MasterCategory'),
        ),
        migrations.AddField(
            model_name='historicalbudgetperiodunit',
            name='category',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='budgetmanagement.SuperCategory'),
        ),
        migrations.AddField(
            model_name='historicalbudgetperiodunit',
            name='expenses_type',
            field=models.IntegerField(blank=True, choices=[(1, b'Programmatic'), (2, b'Non-programmatic')], null=True),
        ),
        migrations.AddField(
            model_name='historicalbudgetperiodunit',
            name='heading',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='projectmanagement.MasterCategory'),
        ),
        migrations.AddField(
            model_name='historicalsupercategory',
            name='parent',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='budgetmanagement.HistoricalSuperCategory'),
        ),
        migrations.AddField(
            model_name='supercategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='budgetmanagement.SuperCategory'),
        ),
        migrations.DeleteModel(
            name='BudgetCategory',
        ),
        migrations.AddField(
            model_name='projectbudgetperiodconf',
            name='budget',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='budgetmanagement.Budget'),
        ),
    ]
