# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-22 05:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanagement', '0004_auto_20170821_1248'),
        ('budgetmanagement', '0003_auto_20170819_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltranche',
            name='project',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='projectmanagement.Project'),
        ),
        migrations.AddField(
            model_name='tranche',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projectmanagement.Project'),
        ),
    ]
