# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-26 09:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budgetmanagement', '0004_auto_20170822_0528'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsupercategory',
            name='budget',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='budgetmanagement.Budget'),
        ),
        migrations.AddField(
            model_name='supercategory',
            name='budget',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='budgetmanagement.Budget'),
        ),
    ]
