# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-28 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetmanagement', '0005_auto_20170826_0933'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budgetperiodunit',
            old_name='order',
            new_name='quarter_order',
        ),
        migrations.RenameField(
            model_name='historicalbudgetperiodunit',
            old_name='order',
            new_name='quarter_order',
        ),
        migrations.AddField(
            model_name='budgetperiodunit',
            name='row_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicalbudgetperiodunit',
            name='row_order',
            field=models.IntegerField(default=0),
        ),
    ]
