# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-28 10:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetmanagement', '0006_auto_20170828_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprojectbudgetperiodconf',
            name='row_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='projectbudgetperiodconf',
            name='row_order',
            field=models.IntegerField(default=0),
        ),
    ]
