# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-30 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetmanagement', '0007_auto_20170828_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetperiodunit',
            name='variance',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='historicalbudgetperiodunit',
            name='variance',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
