# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-04 06:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetmanagement', '0009_projectreport_quarterreportsection_reportmilestoneactivity_reportparameter'),
    ]

    operations = [
        migrations.AddField(
            model_name='quarterreportsection',
            name='quarter_type',
            field=models.IntegerField(blank=True, choices=[(1, b'Previous Quarter Updates'), (2, b'Current Quarter Updates'), (3, b'Future Quarter Updates')], null=True),
        ),
    ]
