# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-04 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetmanagement', '0010_quarterreportsection_quarter_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='quarterreportsection',
            name='quarter_order',
            field=models.IntegerField(default=0),
        ),
    ]
