# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-05 09:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetmanagement', '0011_quarterreportsection_quarter_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportparameter',
            name='parameter_type',
            field=models.TextField(choices=[(b'PIN', b'Pie chart Numbers'), (b'PIP', b'Pie Chart Percent'), (b'NUM', b'Number'), (b'PER', b'Percent'), (b'CUR', b'Currency')], default=b'NUM'),
        ),
    ]
