# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-13 10:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budgetmanagement', '0013_auto_20171013_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='attachment_file',
            field=models.FileField(blank=True, null=True, upload_to=b'static/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='question',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='budgetmanagement.Question'),
        ),
    ]
