# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-13 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetmanagement', '0015_auto_20171013_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='slug',
            field=models.SlugField(blank=True, verbose_name='Slug'),
        ),
    ]
