# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-13 11:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('budgetmanagement', '0017_auto_20171016_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='removequestion',
            name='block_type',
            field=models.IntegerField(choices=[(0, b''), (1, b'CP'), (2, b'PS'), (3, b'PQ'), (4, b'CQ'), (5, b'NQ')], default=0),
        ),
        migrations.AddField(
            model_name='removequestion',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_type_set_for_removequestion', to='contenttypes.ContentType', verbose_name='content type'),
        ),
        migrations.AddField(
            model_name='removequestion',
            name='object_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='object ID'),
        ),
    ]
