# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-14 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetmanagement', '0018_auto_20171213_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='removequestion',
            name='quarter_period',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
