# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-19 07:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('budgetmanagement', '0019_removequestion_quarter_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportmilestoneactivity',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_type_set_for_reportmilestoneactivity', to='contenttypes.ContentType', verbose_name='content type'),
        ),
        migrations.AddField(
            model_name='reportmilestoneactivity',
            name='ma_type',
            field=models.IntegerField(blank=True, choices=[(1, b'Milestone'), (2, b'Activity')], null=True),
        ),
        migrations.AddField(
            model_name='reportmilestoneactivity',
            name='object_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='object ID'),
        ),
    ]
