# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-22 06:56
from __future__ import unicode_literals

from django.db import migrations
import media.models
import private_storage.fields
import private_storage.storage.files


class Migration(migrations.Migration):

    dependencies = [
        ('budgetmanagement', '0024_auto_20180816_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='attachment_file',
            field=private_storage.fields.PrivateFileField(blank=True, max_length=500, null=True, storage=private_storage.storage.files.PrivateFileSystemStorage(), upload_to=media.models.get_file_path),
        ),
    ]
