# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-08 07:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0007_auto_20180816_1632'),
        ('budgetmanagement', '0026_supercategory_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='supercategory',
            name='menu_list',
            field=models.ManyToManyField(blank=True, default=[b'BUDGET', b'TASKS & MILESTONES'], null=True, related_name='super_menu', to='userprofile.Menus'),
        ),
    ]
