# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-08 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetmanagement', '0029_auto_20190808_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supercategory',
            name='menu',
            field=models.ManyToManyField(blank=True, null=True, related_name='super_menu', to='userprofile.Menus'),
        ),
    ]
