# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-02 05:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_userroles'),
    ]

    operations = [
        migrations.AddField(
            model_name='menus',
            name='main_menu',
            field=models.BooleanField(default=True),
        ),
    ]
