# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-22 05:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_menus_main_menu'),
        ('userprofile', '0003_auto_20180216_1135'),
    ]

    operations = [
    ]
