# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-17 05:32
from __future__ import unicode_literals

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Boundary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.PositiveIntegerField(choices=[(0, b'Inactive'), (2, b'Active')], default=2)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('boundary_level', models.IntegerField(default=0)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, verbose_name=b'Slug')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projectmanagement.Boundary')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricalProject',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('active', models.PositiveIntegerField(choices=[(0, b'Inactive'), (2, b'Active')], default=2)),
                ('created', models.DateTimeField(blank=True, editable=False)),
                ('modified', models.DateTimeField(blank=True, editable=False)),
                ('request_status', models.IntegerField(choices=[(0, b''), (1, b'Requested'), (2, b'Request more information'), (3, b'Reject'), (4, b'Approved'), (5, b'ShortList'), (6, b'Decision Pending')], default=0)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('total_budget', models.IntegerField(default=0)),
                ('budget_type', models.IntegerField(choices=[(1, b'Yearly'), (2, b'Quarterly'), (3, b'Half Yearly')], default=2)),
                ('project_status', models.IntegerField(choices=[(0, b''), (1, b'Open'), (2, b'Close'), (3, b'Ongoing')], default=0)),
                ('duration', models.IntegerField(default=0)),
                ('summary', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('no_of_beneficiaries', models.IntegerField(default=0)),
                ('slug', models.SlugField(blank=True, verbose_name='Slug')),
                ('object_id', models.IntegerField(verbose_name='object ID')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('content_type', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contenttypes.ContentType')),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
                'verbose_name': 'historical project',
            },
        ),
        migrations.CreateModel(
            name='HistoricalProjectUserRoleRelationship',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('active', models.PositiveIntegerField(choices=[(0, b'Inactive'), (2, b'Active')], default=2)),
                ('created', models.DateTimeField(blank=True, editable=False)),
                ('modified', models.DateTimeField(blank=True, editable=False)),
                ('role', models.CharField(blank=True, max_length=300, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
                'verbose_name': 'historical project user role relationship',
            },
        ),
        migrations.CreateModel(
            name='KeyParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.PositiveIntegerField(choices=[(0, b'Inactive'), (2, b'Active')], default=2)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='keyParameterValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.PositiveIntegerField(choices=[(0, b'Inactive'), (2, b'Active')], default=2)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('parameter_value', models.CharField(blank=True, max_length=300, null=True)),
                ('object_id', models.IntegerField(verbose_name='object ID')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_type_set_for_keyparametervalue', to='contenttypes.ContentType', verbose_name='content type')),
                ('keyparameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectmanagement.KeyParameter')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MasterCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.PositiveIntegerField(choices=[(0, b'Inactive'), (2, b'Active')], default=2)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('code', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, verbose_name=b'Slug')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projectmanagement.MasterCategory')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PrimaryWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.PositiveIntegerField(choices=[(0, b'Inactive'), (2, b'Active')], default=2)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('types', models.IntegerField(blank=True, choices=[(0, b'Primary Activities'), (1, b'Scope of work')], null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('number', models.IntegerField(default=0)),
                ('activity_duration', models.IntegerField(default=0)),
                ('object_id', models.IntegerField(blank=True, null=True, verbose_name='object ID')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_type_set_for_primarywork', to='contenttypes.ContentType', verbose_name='content type')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.PositiveIntegerField(choices=[(0, b'Inactive'), (2, b'Active')], default=2)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True, verbose_name=b'About Project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.PositiveIntegerField(choices=[(0, b'Inactive'), (2, b'Active')], default=2)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('request_status', models.IntegerField(choices=[(0, b''), (1, b'Requested'), (2, b'Request more information'), (3, b'Reject'), (4, b'Approved'), (5, b'ShortList'), (6, b'Decision Pending')], default=0)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('total_budget', models.IntegerField(default=0)),
                ('budget_type', models.IntegerField(choices=[(1, b'Yearly'), (2, b'Quarterly'), (3, b'Half Yearly')], default=2)),
                ('project_status', models.IntegerField(choices=[(0, b''), (1, b'Open'), (2, b'Close'), (3, b'Ongoing')], default=0)),
                ('duration', models.IntegerField(default=0)),
                ('summary', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('no_of_beneficiaries', models.IntegerField(default=0)),
                ('slug', models.SlugField(blank=True, verbose_name='Slug')),
                ('object_id', models.IntegerField(verbose_name='object ID')),
                ('cause_area', models.ManyToManyField(blank=True, related_name='area_category', to='projectmanagement.MasterCategory')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_type_set_for_project', to='contenttypes.ContentType', verbose_name='content type')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectFunderRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.PositiveIntegerField(choices=[(0, b'Inactive'), (2, b'Active')], default=2)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('total_budget', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectUserRoleRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.PositiveIntegerField(choices=[(0, b'Inactive'), (2, b'Active')], default=2)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(blank=True, max_length=300, null=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projectmanagement.Project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.PositiveIntegerField(choices=[(0, b'Inactive'), (2, b'Active')], default=2)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('user_reference_id', models.IntegerField(default=0)),
                ('email', models.CharField(blank=True, max_length=500, null=True)),
                ('orgnaization', models.CharField(blank=True, max_length=800, null=True)),
                ('organization_type', models.IntegerField(default=0)),
                ('owner', models.BooleanField(default=False)),
                ('is_admin_user', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='projectuserrolerelationship',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projectmanagement.UserProfile'),
        ),
        migrations.AddField(
            model_name='projectfunderrelation',
            name='funder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funder', to='projectmanagement.UserProfile'),
        ),
        migrations.AddField(
            model_name='projectfunderrelation',
            name='implementation_partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='implementation_partner', to='projectmanagement.UserProfile'),
        ),
        migrations.AddField(
            model_name='projectfunderrelation',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projectmanagement.Project'),
        ),
        migrations.AddField(
            model_name='project',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_user', to='projectmanagement.UserProfile'),
        ),
        migrations.AddField(
            model_name='project',
            name='location',
            field=models.ManyToManyField(blank=True, related_name='project_location', to='projectmanagement.Boundary'),
        ),
        migrations.AddField(
            model_name='project',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projectmanagement.Program'),
        ),
        migrations.AddField(
            model_name='project',
            name='target_beneficiaries',
            field=models.ManyToManyField(blank=True, related_name='target_beneficiaries', to='projectmanagement.MasterCategory'),
        ),
        migrations.AddField(
            model_name='program',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='program_created_user', to='projectmanagement.UserProfile'),
        ),
        migrations.AddField(
            model_name='keyparameter',
            name='parameter_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projectmanagement.MasterCategory'),
        ),
        migrations.AddField(
            model_name='keyparameter',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projectmanagement.Project'),
        ),
        migrations.AddField(
            model_name='historicalprojectuserrolerelationship',
            name='project',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='projectmanagement.Project'),
        ),
        migrations.AddField(
            model_name='historicalprojectuserrolerelationship',
            name='user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='projectmanagement.UserProfile'),
        ),
        migrations.AddField(
            model_name='historicalproject',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='projectmanagement.UserProfile'),
        ),
        migrations.AddField(
            model_name='historicalproject',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalproject',
            name='program',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='projectmanagement.Program'),
        ),
    ]
