# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-17 07:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanagement', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='orgnaization',
            new_name='organization',
        ),
    ]
