# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-19 10:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('projectmanagement', '0002_auto_20170817_0716'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.PositiveIntegerField(choices=[(0, b'Inactive'), (2, b'Active')], default=2)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
                ('aggregation_function', models.TextField(blank=True, null=True)),
                ('parameter_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projectmanagement.MasterCategory')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projectmanagement.ProjectParameter')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projectmanagement.Project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectParameterValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.PositiveIntegerField(choices=[(0, b'Inactive'), (2, b'Active')], default=2)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('parameter_value', models.CharField(blank=True, max_length=300, null=True)),
                ('object_id', models.IntegerField(verbose_name='object ID')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_type_set_for_projectparametervalue', to='contenttypes.ContentType', verbose_name='content type')),
                ('keyparameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectmanagement.ProjectParameter')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='keyparameter',
            name='parameter_type',
        ),
        migrations.RemoveField(
            model_name='keyparameter',
            name='project',
        ),
        migrations.RemoveField(
            model_name='keyparametervalue',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='keyparametervalue',
            name='keyparameter',
        ),
        migrations.DeleteModel(
            name='KeyParameter',
        ),
        migrations.DeleteModel(
            name='keyParameterValue',
        ),
    ]
