# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-21 12:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanagement', '0003_auto_20170819_1048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalprojectuserrolerelationship',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalprojectuserrolerelationship',
            name='project',
        ),
        migrations.RemoveField(
            model_name='historicalprojectuserrolerelationship',
            name='user',
        ),
        migrations.RemoveField(
            model_name='projectuserrolerelationship',
            name='project',
        ),
        migrations.RemoveField(
            model_name='projectuserrolerelationship',
            name='user',
        ),
        migrations.DeleteModel(
            name='HistoricalProjectUserRoleRelationship',
        ),
        migrations.DeleteModel(
            name='ProjectUserRoleRelationship',
        ),
    ]
