# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-26 08:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanagement', '0005_auto_20170822_0545'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectparametervalue',
            old_name='name',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='projectparametervalue',
            old_name='date',
            new_name='end_date',
        ),
        migrations.RemoveField(
            model_name='projectparametervalue',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='projectparametervalue',
            name='object_id',
        ),
        migrations.AddField(
            model_name='projectparameter',
            name='instructions',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='projectparametervalue',
            name='has_attachment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectparametervalue',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectparametervalue',
            name='submit_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectparameter',
            name='aggregation_function',
            field=models.TextField(choices=[(b'ADD', b'ADDITION'), (b'AVG', b'AVERAGE'), (b'WAV', b'Weighted Average'), (b'WAP', b'Weighted average over peers')], default=b'ADD'),
        ),
        migrations.AlterField(
            model_name='projectparameter',
            name='parameter_type',
            field=models.TextField(choices=[(b'PIN', b'Pie chart Numbers'), (b'PIP', b'Pie Chart Percent'), (b'NUM', b'Number'), (b'PER', b'Percent'), (b'CUR', b'Currency')], default=b'NUM'),
        ),
        migrations.AlterField(
            model_name='projectparametervalue',
            name='parameter_value',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
