# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-08 06:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanagement', '0007_mastercategory_category_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mastercategory',
            name='category_type',
            field=models.CharField(blank=True, choices=[(b'DBC', b'Direct to Beneficiary Cost'), (b'IC', b'Indirect Cost'), (b'AC', b'Admin Cost'), (b'O', b'Others')], max_length=100, null=True),
        ),
    ]
