# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-13 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanagement', '0008_auto_20170908_0628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproject',
            name='name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproject',
            name='slug',
            field=models.SlugField(blank=True, max_length=300, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, max_length=300, verbose_name='Slug'),
        ),
    ]
