# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-06 07:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projectmanagement', '0012_auto_20180216_1135'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalProjectParameter',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('active', models.PositiveIntegerField(choices=[(0, b'Inactive'), (2, b'Active')], default=2)),
                ('created', models.DateTimeField(blank=True, editable=False)),
                ('modified', models.DateTimeField(blank=True, editable=False)),
                ('modified_by', models.CharField(blank=True, max_length=50, null=True)),
                ('parameter_type', models.TextField(choices=[(b'PIN', b'Pie chart Numbers'), (b'PIP', b'Pie Chart Percent'), (b'NUM', b'Number'), (b'PER', b'Percent'), (b'CUR', b'Currency')], default=b'NUM')),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
                ('aggregation_function', models.TextField(choices=[(b'ADD', b'ADDITION'), (b'AVG', b'AVERAGE'), (b'WAV', b'Weighted Average'), (b'WAP', b'Weighted average over peers')], default=b'ADD')),
                ('instructions', models.CharField(blank=True, max_length=300, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='projectmanagement.HistoricalProjectParameter')),
                ('project', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='projectmanagement.Project')),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
                'verbose_name': 'historical project parameter',
            },
        ),
    ]
