# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-16 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanagement', '0013_historicalprojectparameter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boundary',
            name='active',
            field=models.PositiveIntegerField(choices=[(0, b'Inactive'), (2, b'Active')], db_index=True, default=2),
        ),
        migrations.AlterField(
            model_name='historicalproject',
            name='active',
            field=models.PositiveIntegerField(choices=[(0, b'Inactive'), (2, b'Active')], db_index=True, default=2),
        ),
        migrations.AlterField(
            model_name='historicalprojectparameter',
            name='active',
            field=models.PositiveIntegerField(choices=[(0, b'Inactive'), (2, b'Active')], db_index=True, default=2),
        ),
        migrations.AlterField(
            model_name='mastercategory',
            name='active',
            field=models.PositiveIntegerField(choices=[(0, b'Inactive'), (2, b'Active')], db_index=True, default=2),
        ),
        migrations.AlterField(
            model_name='primarywork',
            name='active',
            field=models.PositiveIntegerField(choices=[(0, b'Inactive'), (2, b'Active')], db_index=True, default=2),
        ),
        migrations.AlterField(
            model_name='program',
            name='active',
            field=models.PositiveIntegerField(choices=[(0, b'Inactive'), (2, b'Active')], db_index=True, default=2),
        ),
        migrations.AlterField(
            model_name='project',
            name='active',
            field=models.PositiveIntegerField(choices=[(0, b'Inactive'), (2, b'Active')], db_index=True, default=2),
        ),
        migrations.AlterField(
            model_name='projectfunderrelation',
            name='active',
            field=models.PositiveIntegerField(choices=[(0, b'Inactive'), (2, b'Active')], db_index=True, default=2),
        ),
        migrations.AlterField(
            model_name='projectparameter',
            name='active',
            field=models.PositiveIntegerField(choices=[(0, b'Inactive'), (2, b'Active')], db_index=True, default=2),
        ),
        migrations.AlterField(
            model_name='projectparametervalue',
            name='active',
            field=models.PositiveIntegerField(choices=[(0, b'Inactive'), (2, b'Active')], db_index=True, default=2),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='active',
            field=models.PositiveIntegerField(choices=[(0, b'Inactive'), (2, b'Active')], db_index=True, default=2),
        ),
    ]
