# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-30 08:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanagement', '0016_auto_20180816_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='org_logo',
            field=models.FileField(blank=True, null=True, upload_to=b'static/%Y/%m/%d'),
        ),
    ]
