# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-03 04:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanagement', '0017_userprofile_org_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproject',
            name='logo',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to=b'static/%Y/%m/%d'),
        ),
    ]
