# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-11 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanagement', '0018_auto_20190103_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprojectparameter',
            name='is_beneficiary_type',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectparameter',
            name='is_beneficiary_type',
            field=models.BooleanField(default=False),
        ),
    ]
