# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-15 12:53
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanagement', '0019_auto_20190111_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprojectparameter',
            name='custom_html',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectparameter',
            name='custom_html',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalprojectparameter',
            name='parameter_type',
            field=models.TextField(choices=[(b'PIN', b'Pie chart Numbers'), (b'PIP', b'Pie Chart Percent'), (b'NUM', b'Number'), (b'PER', b'Percent'), (b'CUR', b'Currency'), (b'HTML', b'Custom HTML')], default=b'NUM'),
        ),
        migrations.AlterField(
            model_name='projectparameter',
            name='parameter_type',
            field=models.TextField(choices=[(b'PIN', b'Pie chart Numbers'), (b'PIP', b'Pie Chart Percent'), (b'NUM', b'Number'), (b'PER', b'Percent'), (b'CUR', b'Currency'), (b'HTML', b'Custom HTML')], default=b'NUM'),
        ),
    ]
