# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-17 09:36
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanagement', '0020_auto_20190515_1823'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.PositiveIntegerField(choices=[(0, b'Inactive'), (2, b'Active')], db_index=True, default=2)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(blank=True, max_length=50, null=True)),
                ('html_parameter', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('nos_column', models.PositiveIntegerField(choices=[(b'col-md-12', b'12'), (b'col-md-6', b'6'), (b'col-md-4', b'4')], default=12)),
                ('order', models.PositiveIntegerField(blank=True, null=True)),
                ('link', models.URLField(blank=True, verbose_name=b'Link url')),
                ('keyparameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectmanagement.ProjectParameter')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
