# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-17 10:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanagement', '0021_projectblock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalprojectparameter',
            name='custom_html',
        ),
        migrations.RemoveField(
            model_name='projectparameter',
            name='custom_html',
        ),
    ]
