# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-17 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanagement', '0022_auto_20190517_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectblock',
            name='nos_column',
            field=models.PositiveIntegerField(choices=[(b'12', b'col-md-12'), (b'6', b'col-md-6'), (b'4', b'col-md-4')], default=12),
        ),
    ]
