# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-17 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanagement', '0023_auto_20190517_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectblock',
            name='nos_column',
            field=models.CharField(choices=[(b'col-md-12', b'12'), (b'col-md-6', b'6'), (b'col-md-4', b'4')], default=12, max_length=12),
        ),
    ]
