# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-23 07:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanagement', '0025_projectblock_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectblock',
            name='nos_column',
        ),
        migrations.AddField(
            model_name='projectblock',
            name='html_class',
            field=models.CharField(default=12, max_length=12),
        ),
    ]
