# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-23 07:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanagement', '0026_auto_20190523_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectblock',
            name='html_class',
            field=models.CharField(default=b'col-md-12', max_length=12),
        ),
    ]
