# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-08 05:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanagement', '0028_auto_20190523_1347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalproject',
            name='program',
        ),
        migrations.RemoveField(
            model_name='project',
            name='program',
        ),
        migrations.AddField(
            model_name='project',
            name='program',
            field=models.ManyToManyField(blank=True, null=True, related_name='project_program', to='projectmanagement.Program'),
        ),
    ]
