# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-19 10:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanagement', '0003_auto_20170819_1048'),
        ('taskmanagement', '0002_auto_20170818_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='subscribers',
            field=models.ManyToManyField(blank=True, related_name='activity_subscriber_user', to='projectmanagement.UserProfile'),
        ),
        migrations.AddField(
            model_name='historicalmilestone',
            name='status',
            field=models.IntegerField(choices=[(0, b' '), (1, b'Open'), (2, b'Close'), (3, b'Ongoing')], default=0),
        ),
        migrations.AddField(
            model_name='milestone',
            name='status',
            field=models.IntegerField(choices=[(0, b' '), (1, b'Open'), (2, b'Close'), (3, b'Ongoing')], default=0),
        ),
        migrations.AddField(
            model_name='milestone',
            name='subscribers',
            field=models.ManyToManyField(blank=True, related_name='milestone_subscriber_user', to='projectmanagement.UserProfile'),
        ),
        migrations.AddField(
            model_name='task',
            name='subscribers',
            field=models.ManyToManyField(blank=True, related_name='task_subscriber_user', to='projectmanagement.UserProfile'),
        ),
        migrations.AddField(
            model_name='task',
            name='task_dependency',
            field=models.ManyToManyField(blank=True, related_name='_task_task_dependency_+', to='taskmanagement.Task'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_asigned_user', to='projectmanagement.UserProfile'),
        ),
    ]
