# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-24 07:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanagement', '0003_auto_20170819_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmilestone',
            name='slug',
            field=models.SlugField(blank=True, verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='historicaltask',
            name='task_dependency',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='taskmanagement.HistoricalTask'),
        ),
        migrations.AddField(
            model_name='milestone',
            name='slug',
            field=models.SlugField(blank=True, verbose_name='Slug'),
        ),
        migrations.RemoveField(
            model_name='task',
            name='task_dependency',
        ),
        migrations.AddField(
            model_name='task',
            name='task_dependency',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='taskmanagement.Task'),
            preserve_default=False,
        ),
    ]
