# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-24 10:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanagement', '0004_auto_20170824_0715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_dependency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='taskmanagement.Task'),
        ),
    ]
