# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-30 06:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanagement', '0005_auto_20170824_1004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaltask',
            name='task_dependency',
        ),
        migrations.RemoveField(
            model_name='task',
            name='task_dependency',
        ),
        migrations.AddField(
            model_name='task',
            name='task_dependency',
            field=models.ManyToManyField(blank=True, related_name='_task_task_dependency_+', to='taskmanagement.Task'),
        ),
    ]
