# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-31 14:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanagement', '0006_auto_20170826_0813'),
        ('taskmanagement', '0006_auto_20170830_0606'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmilestone',
            name='project',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='projectmanagement.Project'),
        ),
        migrations.AddField(
            model_name='milestone',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projectmanagement.Project'),
        ),
    ]
