# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-05 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanagement', '0007_auto_20170831_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='slug',
            field=models.SlugField(blank=True, max_length=600, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='historicalactivity',
            name='slug',
            field=models.SlugField(blank=True, max_length=600, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='historicalmilestone',
            name='slug',
            field=models.SlugField(blank=True, max_length=600, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='historicaltask',
            name='slug',
            field=models.SlugField(blank=True, max_length=600, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='slug',
            field=models.SlugField(blank=True, max_length=600, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='task',
            name='slug',
            field=models.SlugField(blank=True, max_length=600, verbose_name='Slug'),
        ),
    ]
