# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-13 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanagement', '0009_auto_20170908_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_dependency',
            field=models.ManyToManyField(blank=True, to='taskmanagement.Task'),
        ),
    ]
