# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-16 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanagement', '0010_auto_20170913_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='modified_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historicalactivity',
            name='modified_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historicalmilestone',
            name='modified_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historicaltask',
            name='modified_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='milestone',
            name='modified_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='modified_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
