# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-16 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanagement', '0013_auto_20180816_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='active',
            field=models.PositiveIntegerField(choices=[(0, b'Inactive'), (2, b'Active')], db_index=True, default=2),
        ),
        migrations.AlterField(
            model_name='historicalactivity',
            name='active',
            field=models.PositiveIntegerField(choices=[(0, b'Inactive'), (2, b'Active')], db_index=True, default=2),
        ),
        migrations.AlterField(
            model_name='historicalmilestone',
            name='active',
            field=models.PositiveIntegerField(choices=[(0, b'Inactive'), (2, b'Active')], db_index=True, default=2),
        ),
        migrations.AlterField(
            model_name='historicaltask',
            name='active',
            field=models.PositiveIntegerField(choices=[(0, b'Inactive'), (2, b'Active')], db_index=True, default=2),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='active',
            field=models.PositiveIntegerField(choices=[(0, b'Inactive'), (2, b'Active')], db_index=True, default=2),
        ),
        migrations.AlterField(
            model_name='task',
            name='active',
            field=models.PositiveIntegerField(choices=[(0, b'Inactive'), (2, b'Active')], db_index=True, default=2),
        ),
    ]
