# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-17 05:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projectmanagement', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectlocation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projectmanagement.UserProfile'),
        ),
        migrations.AddField(
            model_name='projectlocation',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projectmanagement.Boundary'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_type_set_for_attachment', to='contenttypes.ContentType', verbose_name='content type'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='media.Attachment'),
        ),
    ]
