# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-21 12:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanagement', '0003_auto_20170819_1048'),
        ('media', '0003_auto_20170821_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_created_user', to='projectmanagement.UserProfile'),
        ),
    ]
