# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-30 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0005_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='name',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name=b'Name'),
        ),
    ]
