# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-21 06:17
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import thumbs


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0007_comment_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.PositiveIntegerField(choices=[(0, b'Inactive'), (2, b'Active')], default=2)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=300, null=True, verbose_name=b'Name')),
                ('description', models.TextField(blank=True, null=True)),
                ('listing_order', models.IntegerField(blank=True, default=0, null=True)),
                ('slug', models.SlugField(blank=True, verbose_name='Slug')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='media.Article')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.PositiveIntegerField(choices=[(0, b'Inactive'), (2, b'Active')], default=2)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=300, null=True, verbose_name=b'Name')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('summary', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('cover_image', thumbs.ImageWithThumbsField(blank=True, help_text=b'Image size should be 930x300 pixels', null=True, upload_to=b'static/%Y/%m/%d')),
                ('image', thumbs.ImageWithThumbsField(blank=True, help_text=b'Image size should be 930x300 pixels', null=True, upload_to=b'static/%Y/%m/%d')),
                ('listing_order', models.IntegerField(blank=True, default=0, null=True)),
                ('slug', models.SlugField(blank=True, verbose_name='Slug')),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='media.Article')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
