# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-22 06:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0008_article_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPersonInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.PositiveIntegerField(choices=[(0, b'Inactive'), (2, b'Active')], default=2)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=300, null=True, verbose_name=b'Name')),
                ('email', models.CharField(blank=True, max_length=500, null=True, verbose_name=b'Email')),
                ('organization_name', models.CharField(blank=True, max_length=600, null=True, verbose_name=b'Organization Name')),
                ('mobile_number', models.CharField(blank=True, max_length=50, null=True, verbose_name=b'Mobile Number')),
                ('message', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
