# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-30 09:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('budgetmanagement', '0017_auto_20171016_1049'),
        ('media', '0009_contactpersoninformation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScreenshotMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.PositiveIntegerField(choices=[(0, b'Inactive'), (2, b'Active')], default=2)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('attachment_file', models.FileField(blank=True, null=True, upload_to=b'static/%Y/%m/%d')),
                ('object_id', models.IntegerField(blank=True, null=True, verbose_name='object ID')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_type_set_for_screenshotmedia', to='contenttypes.ContentType', verbose_name='content type')),
                ('report_parameter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='budgetmanagement.ReportParameter')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
