# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-30 11:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0010_screenshotmedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='screenshotmedia',
            name='img_file_path',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
