# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-04 06:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0011_screenshotmedia_img_file_path'),
        ('media', '0010_attachment_timeline_progress'),
    ]

    operations = [
    ]
