# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-13 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0012_merge_20171204_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='timeline_progress',
            field=models.BooleanField(default=True),
        ),
    ]
