# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-15 07:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanagement', '0011_auto_20171113_1254'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('media', '0013_auto_20171213_1125'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalAttachment',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('active', models.PositiveIntegerField(choices=[(0, b'Inactive'), (2, b'Active')], default=2)),
                ('created', models.DateTimeField(blank=True, editable=False)),
                ('modified', models.DateTimeField(blank=True, editable=False)),
                ('attachment_file', models.TextField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=300, null=True, verbose_name=b'Name')),
                ('description', models.CharField(blank=True, max_length=600, null=True, verbose_name=b'Description')),
                ('attachment_type', models.IntegerField(blank=True, choices=[(1, b'Image'), (2, b'Documents')], null=True, verbose_name=b'ATTACHMENT_TYPE')),
                ('document_type', models.IntegerField(blank=True, choices=[(1, b'Excel'), (2, b'PDF'), (3, b'PPT'), (4, b'Word Document')], null=True, verbose_name=b'DOCUMENT_TYPE')),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('object_id', models.IntegerField(blank=True, null=True, verbose_name='object ID')),
                ('URL', models.URLField(blank=True, verbose_name=b'Link url')),
                ('timeline_progress', models.BooleanField(default=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('content_type', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contenttypes.ContentType')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='projectmanagement.UserProfile')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='media.HistoricalAttachment')),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
                'verbose_name': 'historical attachment',
            },
        ),
    ]
