# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-16 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0016_historicalnote_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='active',
            field=models.PositiveIntegerField(choices=[(0, b'Inactive'), (2, b'Active')], db_index=True, default=2),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='active',
            field=models.PositiveIntegerField(choices=[(0, b'Inactive'), (2, b'Active')], db_index=True, default=2),
        ),
        migrations.AlterField(
            model_name='comment',
            name='active',
            field=models.PositiveIntegerField(choices=[(0, b'Inactive'), (2, b'Active')], db_index=True, default=2),
        ),
        migrations.AlterField(
            model_name='contactpersoninformation',
            name='active',
            field=models.PositiveIntegerField(choices=[(0, b'Inactive'), (2, b'Active')], db_index=True, default=2),
        ),
        migrations.AlterField(
            model_name='filekeywords',
            name='active',
            field=models.PositiveIntegerField(choices=[(0, b'Inactive'), (2, b'Active')], db_index=True, default=2),
        ),
        migrations.AlterField(
            model_name='historicalattachment',
            name='active',
            field=models.PositiveIntegerField(choices=[(0, b'Inactive'), (2, b'Active')], db_index=True, default=2),
        ),
        migrations.AlterField(
            model_name='historicalnote',
            name='active',
            field=models.PositiveIntegerField(choices=[(0, b'Inactive'), (2, b'Active')], db_index=True, default=2),
        ),
        migrations.AlterField(
            model_name='keywords',
            name='active',
            field=models.PositiveIntegerField(choices=[(0, b'Inactive'), (2, b'Active')], db_index=True, default=2),
        ),
        migrations.AlterField(
            model_name='note',
            name='active',
            field=models.PositiveIntegerField(choices=[(0, b'Inactive'), (2, b'Active')], db_index=True, default=2),
        ),
        migrations.AlterField(
            model_name='projectlocation',
            name='active',
            field=models.PositiveIntegerField(choices=[(0, b'Inactive'), (2, b'Active')], db_index=True, default=2),
        ),
        migrations.AlterField(
            model_name='screenshotmedia',
            name='active',
            field=models.PositiveIntegerField(choices=[(0, b'Inactive'), (2, b'Active')], db_index=True, default=2),
        ),
        migrations.AlterField(
            model_name='section',
            name='active',
            field=models.PositiveIntegerField(choices=[(0, b'Inactive'), (2, b'Active')], db_index=True, default=2),
        ),
    ]
