# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-16 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0019_auto_20180816_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='object_id',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='object ID'),
        ),
        migrations.AlterField(
            model_name='historicalattachment',
            name='object_id',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='object ID'),
        ),
    ]
