# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-28 04:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0020_auto_20180816_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='attachment_file',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=b'get_file_path'),
        ),
        migrations.AlterField(
            model_name='historicalattachment',
            name='attachment_file',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
