# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-22 06:56
from __future__ import unicode_literals

from django.db import migrations, models
import media.models
import private_storage.fields
import private_storage.storage.files


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0021_auto_20190328_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='attachment_file',
            field=private_storage.fields.PrivateFileField(blank=True, max_length=500, null=True, storage=private_storage.storage.files.PrivateFileSystemStorage(), upload_to=media.models.get_file_path),
        ),
        migrations.AlterField(
            model_name='historicalattachment',
            name='attachment_file',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='historicalnote',
            name='attachment_file',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='attachment_file',
            field=private_storage.fields.PrivateFileField(blank=True, max_length=500, null=True, storage=private_storage.storage.files.PrivateFileSystemStorage(), upload_to=media.models.get_file_path),
        ),
    ]
